import type { Metadata } from "next";

import "./globals.css";
import AuthSessionProvider from "@/components/providers/SessionProvder";
import RegisterModel from "@/components/models/RegisterModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthSessionProvider>
          <RegisterModel />
          {children}
        </AuthSessionProvider>
      </body>
    </html>
  );
}
