import type { Metadata } from "next";

import Navber from "@/components/Header/Navbar";
import AuthSessionProvider from "@/components/providers/SessionProvder";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} antialiased `}>
        <AuthSessionProvider>
          <Toaster duration={3000}/>
          <Navber />
          {children}
        </AuthSessionProvider>
      </body>
    </html>
  );
}
